# Generated by Django 2.0.7 on 2019-05-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saalis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saaja', models.CharField(max_length=300)),
                ('paikka', models.CharField(max_length=30)),
                ('paino', models.CharField(max_length=10)),
                ('pituus', models.CharField(max_length=10)),
                ('viehe', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('saantipaiva', models.DateField()),
                ('kuva', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('public', models.BooleanField()),
            ],
            options={
                'permissions': (('publih', 'Allows publishing of saalistilasto objects'),),
            },
        ),
    ]
