# Generated by Django 2.0.13 on 2020-06-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saalistilastot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saalis',
            name='sukupuoli',
            field=models.CharField(choices=[('U', 'U'), ('N', 'N'), ('?', '?')], default='?', max_length=1),
        ),
    ]
