# Generated by Django 2.0.13 on 2020-06-17 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saalistilastot', '0002_saalis_sukupuoli'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saalis',
            options={'permissions': (('publish', 'Allows publishing of saalistilasto objects'),)},
        ),
        migrations.AlterField(
            model_name='saalis',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='saalis',
            name='saantipaiva',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='saalis',
            name='sukupuoli',
            field=models.CharField(choices=[('U', 'U'), ('N', 'N'), ('-', '-')], default='?', max_length=1),
        ),
    ]
