# Generated by Django 2.0.13 on 2020-06-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saalistilastot', '0003_auto_20200617_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saalis',
            name='sukupuoli',
            field=models.CharField(choices=[('U', 'U'), ('N', 'N'), ('-', '-')], default='-', max_length=1),
        ),
    ]
