# Generated by Django 2.0.13 on 2020-06-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saalistilastot', '0004_auto_20200617_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saalis',
            name='paikka',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='saalis',
            name='paino',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='saalis',
            name='pituus',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='saalis',
            name='saaja',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='saalis',
            name='viehe',
            field=models.CharField(max_length=20),
        ),
    ]
