# Generated by Django 2.0.13 on 2020-06-29 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saalistilastot', '0005_auto_20200626_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saalis',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='saalis',
            name='pituus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='saalis',
            name='saantipaiva',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='saalis',
            name='viehe',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
