# Generated by Django 2.0.13 on 2020-06-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saalistilastot', '0006_auto_20200629_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saalis',
            name='viehe',
            field=models.CharField(blank=True, default='-', max_length=20),
        ),
    ]
