# Generated by Django 2.0.13 on 2020-07-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saalistilastot', '0010_auto_20200702_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saalis',
            name='paino',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
