# Generated by Django 2.0.13 on 2020-07-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saalistilastot', '0011_auto_20200702_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saalis',
            name='pituus',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
